project_id = "knazotjkjvhidgfpsiyw"

[functions.generate-product-description]
verify_jwt = false

[functions.generate-product-image]
verify_jwt = false

[functions.generate-product-features]
verify_jwt = false
